name: commerce_mentor_admin
description: Admin Panel for Commerce Mentor App
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  provider: ^6.0.5
  image_picker: ^1.0.1
  file_picker: ^5.3.2
  intl: ^0.18.1
  flutter_quill: ^7.2.11
  cached_network_image: ^3.2.3
  uuid: ^3.0.7
  excel: ^2.1.0
  pdf: ^3.10.4
  charts_flutter: ^0.12.0
  url_launcher: ^6.1.12
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
